import { type NextRequest, NextResponse } from "next/server"
import { GoogleGenerativeAI } from "@google/generative-ai"

export async function POST(request: NextRequest) {
  try {
    const { resumeData, position, difficulty = "medium", questionCount = 5 } = await request.json()

    if (!position) {
      return NextResponse.json({ error: "Position is required" }, { status: 400 })
    }

    const apiKey = process.env.GEMINI_API_KEY

    // Check if API key is properly configured
    if (!apiKey || apiKey === "your_gemini_api_key_here" || apiKey.length < 10) {
      console.log("Gemini API key not configured, using fallback questions")
      const fallbackQuestions = generateFallbackQuestions(position, difficulty, questionCount)
      return NextResponse.json({
        questions: fallbackQuestions,
        message: "Using fallback questions - configure Gemini API key for AI-generated questions",
      })
    }

    try {
      const genAI = new GoogleGenerativeAI(apiKey)
      const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" })

      const prompt = `
Generate ${questionCount} interview questions for a ${position} position with ${difficulty} difficulty.

${
  resumeData
    ? `
Candidate Background:
- Experience: ${resumeData.experience?.map((exp: any) => `${exp.position} at ${exp.company}`).join(", ") || "Not provided"}
- Skills: ${resumeData.skills?.join(", ") || "Not provided"}
`
    : ""
}

Difficulty: ${difficulty} (easy=entry level, medium=mid level, hard=senior level)

Return ONLY a JSON array with this structure:
[
  {
    "id": "1",
    "question": "Question text here",
    "type": "technical",
    "expectedDuration": 120,
    "followUp": "Follow-up question",
    "hints": ["Hint 1", "Hint 2"]
  }
]

Question types: technical (60%), behavioral (25%), situational (15%)
Make questions fair, unbiased, and relevant to ${position}.
`

      const result = await model.generateContent(prompt)
      const response = await result.response
      const text = response.text()

      try {
        // Clean and extract JSON
        const cleanedText = text.replace(/```json\n?|\n?```/g, "").trim()
        const jsonMatch = cleanedText.match(/\[[\s\S]*\]/)

        if (!jsonMatch) {
          throw new Error("No valid JSON array found")
        }

        const questions = JSON.parse(jsonMatch[0])

        if (!Array.isArray(questions) || questions.length === 0) {
          throw new Error("Invalid questions format")
        }

        // Validate and clean questions
        const validatedQuestions = questions.slice(0, questionCount).map((q, index) => ({
          id: q.id || (index + 1).toString(),
          question: q.question || `Sample question for ${position}`,
          type: q.type || "technical",
          expectedDuration: q.expectedDuration || 120,
          followUp: q.followUp || "Can you elaborate on that?",
          hints: Array.isArray(q.hints) ? q.hints : ["Think about your experience", "Consider best practices"],
        }))

        return NextResponse.json({
          questions: validatedQuestions,
          message: "Questions generated by AI",
        })
      } catch (parseError) {
        console.error("Error parsing AI response:", parseError)
        throw parseError
      }
    } catch (aiError) {
      console.error("AI generation error:", aiError)
      throw aiError
    }
  } catch (error) {
    console.error("Error generating questions:", error)

    // Always provide fallback questions
    const fallbackQuestions = generateFallbackQuestions(position, difficulty, questionCount)
    return NextResponse.json({
      questions: fallbackQuestions,
      message: "Using fallback questions due to AI error",
    })
  }
}

function generateFallbackQuestions(position: string, difficulty: string, questionCount: number) {
  const positionName = position.replace("-", " ")

  const questions = [
    {
      id: "1",
      question: `Tell me about your experience with ${positionName} and what interests you about this role.`,
      type: "behavioral",
      expectedDuration: 120,
      followUp: "What specific aspects do you find most challenging?",
      hints: ["Focus on relevant experience", "Mention specific technologies"],
    },
    {
      id: "2",
      question: "Describe a challenging project you worked on recently and how you overcame the obstacles.",
      type: "situational",
      expectedDuration: 180,
      followUp: "What would you do differently next time?",
      hints: ["Use the STAR method", "Focus on your contributions", "Highlight problem-solving"],
    },
    {
      id: "3",
      question: "How do you stay updated with the latest technologies and industry trends?",
      type: "behavioral",
      expectedDuration: 90,
      followUp: "Can you give an example of something new you learned recently?",
      hints: ["Mention specific resources", "Show continuous learning", "Demonstrate passion"],
    },
    {
      id: "4",
      question: `What do you think are the most important skills for a ${positionName}?`,
      type: "technical",
      expectedDuration: 120,
      followUp: "How do you demonstrate these skills in your work?",
      hints: ["Think about both technical and soft skills", "Relate to the job requirements"],
    },
    {
      id: "5",
      question: "Describe a time when you had to work with a difficult team member or stakeholder.",
      type: "behavioral",
      expectedDuration: 150,
      followUp: "What did you learn from that experience?",
      hints: ["Focus on communication", "Show emotional intelligence", "Highlight resolution"],
    },
  ]

  return questions.slice(0, questionCount)
}
